<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ резюме из HeadHunter

In [69]:
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objs as go

# Исследование структуры данных

1. Прочитайте данные с помощью библиотеки Pandas. Совет: перед чтением обратите внимание на разделитель внутри файла.

In [70]:
# Посмотрим первые строки файла:
with open('dst-3.0_16_1_hh_database.csv', 'r', encoding='utf-8') as f:
    for i in range(5):
        print(f.readline())

Пол, возраст;ЗП;Ищет работу на должность:;Город, переезд, командировки;Занятость;График;Опыт работы;Последнее/нынешнее место работы;Последняя/нынешняя должность;Образование и ВУЗ;Обновление резюме;Авто

Мужчина ,  39 лет , родился 27 ноября 1979;29000 руб.;Системный администратор;Советск (Калининградская область) , не готов к переезду , не готов к командировкам;частичная занятость, проектная работа, полная занятость;гибкий график, полный день, сменный график, вахтовый метод, удаленная работа;"Опыт работы 16 лет 10 месяцев  Август 2010 — по настоящее время 8 лет 10 месяцев МАОУ ""СОШ № 1 г.Немана"" Системный администратор Обслуживание ПК,установка ПО, ремонт, периферийной техники, Интернет локальная сеть. Ведение Электронного журнала, сайта организации.  Август 2002 — Август  2010 8 лет 1 месяц ТС ""ВЕСТЕР-ИНФО"" Старший продавец, директор отдела Продажи компьютерной техники";"МАОУ ""СОШ № 1 г.Немана""";Системный администратор;Неоконченное высшее образование 2000  Балтийская государственная академия рыбопромыслового флота, Калининград судоводительский, Организация и безопасность движения;16.04.2019 15:59;Имеется собственный автомобиль

Мужчина ,  60 лет , родился 20 марта 1959;40000 руб.;Технический писатель;Королев , не готов к переезду , готов к редким командировкам;частичная занятость, проектная работа, полная занятость;гибкий график, полный день, сменный график, удаленная работа;Опыт работы 19 лет 5 месяцев  Январь 2000 — по настоящее время 19 лет 5 месяцев Временный трудовой коллектив Москва Информационные технологии, системная интеграция, интернет ... Разработка программного обеспечения Системная интеграция, автоматизации технологических и бизнес-процессов предприятия, ИТ-консалтинг Менеджер проекта, Аналитик, Технический писатель Весь цикл ПО, кроме программирования.;Временный трудовой коллектив;Менеджер проекта, Аналитик, Технический писатель;Высшее образование 1981  Военно-космическая академия им. А.Ф. Можайского, Санкт-Петербург АСУ, АСУ;12.04.2019 08:42;Не указано

Женщина ,  36 лет , родилась 12 августа 1982;20000 руб.;Оператор;Тверь , не готова к переезду , не готова к командировкам;полная занятость;полный день;Опыт работы 10 лет 3 месяца  Октябрь 2004 — Декабрь  2014 10 лет 3 месяца ПАО Сбербанк Кассир-операционист Работа с денежной наличностью, обслуживание клиентов, операции с иностранной валютой, проведение инкассации, составление и обработка первичных документов.;ПАО Сбербанк;Кассир-операционист;Среднее специальное образование 2002 Профессиональный лицей 39 г. Твери Экономический, Банковское дело;16.04.2019 08:35;Не указано

Мужчина ,  38 лет , родился 25 июня 1980;100000 руб.;"Веб-разработчик (HTML / CSS / JS / PHP / базы данных; фреймворки, дизайн, интерфейсы, CMS)";Саратов , не готов к переезду , готов к редким командировкам;частичная занятость, проектная работа, полная занятость;гибкий график, удаленная работа;"Опыт работы 18 лет 9 месяцев  Август 2017 — Апрель  2019 1 год 9 месяцев OpenSoft Саратов , www.opensoftdev.ru Информационные технологии, системная интеграция, интернет ... Системная интеграция, автоматизации технологических и бизнес-процессов предприятия, ИТ-консалтинг Инженер-программист Разработка и поддержка сайтов на корпоративной CMS и на WordPress; разработка корпоративной CMS; дизайн, вёрстка, улучшение интерфейсов существующих сайтов, основанных на разных фреймворках и CMS; консультации и техническая поддержка.  Октябрь 2006 — Июнь  2018 11 лет 9 месяцев СГУ им. Н.Г. Чернышевского Саратовская область , www.sgu.ru/ Преподаватель, научный руководитель Преподаватель (растровая компьютерная графика, разработка интерфейсов, PHP, JavaScript, фотография и др. дисциплины)  Июнь 2013 — Сентябрь  2017 4 года 4 месяца MIF Technology miftechnology.com/ Информационные технологии, системная интеграция, интернет ... Разработка программного обеспечения Системная интеграция, автоматизации технологических и бизнес-процессов предприятия, ИТ-консалтинг Веб-разработчик Веб-разработка широкого профиля: проектирование, дизайн, вёрстка, многоязычные системы, базы данных, программирование, тестирование, консультации, техническая поддержка.  Апрель 2012 — Август  2012 5 месяцев Веб-Синергия Саратов Информационные технологии, системная интеграция, интернет ... Разработка программного обеспечения Веб-разработчик Полноценная разработка веб-приложения, посвящённого поиску и заказу книг в различных электронных библиотеках.  Сентябрь 2010 — Март  2012 1 год 7 месяцев IRESSOURCES Франция , iressources.com Веб-разработчик, верстальщик Вёрстка веб-страниц (кроссбраузерная, адаптивная, кроссплатформенная) для сложных макетов, дизайн, разработка социальных сетей и фрагментов сайтов (мультиязычных и на французском / английском языках).  Апрель 2008 — Август  2010 2 года 5 месяцев ЛАР, ООО Россия , www.lar.ru Верстальщик Вёрстка веб-страниц (кроссбраузерная, кроссскринная, кроссплатформенная) для сложных макетов, дизайн, разработка веб-приложений на PHP / MySQL.  Август 2005 — Март  2008 2 года 8 месяцев ГУ РОПЕ «Неделя области» Саратов , www.nedelia.ru Верстальщик, веб-дизайнер, выпускающий редактор Полиграфическая вёрстка, создание и поддержка сайта газеты  Сентябрь 2002 — Июль  2005 2 года 11 месяцев ООО «Медиа-Саратов» Саратов , www.bogatej.ru/ Верстальщик, веб-дизайнер, корректор Полиграфическая вёрстка, создание и поддержка сайта газеты  Январь 2002 — Май  2004 2 года 5 месяцев Школа №105 Саратов Образовательные учреждения ... Школа, детский сад Учитель информатики Собственный курс, включающий основы веб-разработки.";OpenSoft;Инженер-программист;Высшее образование 2002  Саратовский государственный университет им. Н.Г. Чернышевского, Саратов Филологический, филология (лингвистика), Красный диплом, специализация: филолог (лингвист), доп. специализация: информационные технологии в филологии;08.04.2019 14:23;Не указано

In [71]:
#Прочитайте данные с помощью библиотеки Pandas. Перед чтением обратите внимание на разделитель внутри файла. Чему равна размерность таблицы? 
df_resume = pd.read_csv('dst-3.0_16_1_hh_database.csv'
    , sep=';'
    , quotechar = '"'
    , engine ='python'
    , doublequote = True
    )
df_resume.shape

(44744, 12)

2. Выведите несколько первых (последних) строк таблицы, чтобы убедиться в том, что ваши данные не повреждены. Ознакомьтесь с признаками и их структурой.

In [72]:
# ваш код здесь
df_resume.head(3)

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано

3. Выведите основную информацию о числе непустых значений в столбцах и их типах в таблице.

In [73]:
df_resume.info()

<class 'pandas.DataFrame'>
RangeIndex: 44744 entries, 0 to 44743
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Пол, возраст                     44744 non-null  str
 1   ЗП                               44744 non-null  str
 2   Ищет работу на должность:        44744 non-null  str
 3   Город, переезд, командировки     44744 non-null  str
 4   Занятость                        44744 non-null  str
 5   График                           44744 non-null  str
 6   Опыт работы                      44576 non-null  str
 7   Последнее/нынешнее место работы  44743 non-null  str
 8   Последняя/нынешняя должность     44742 non-null  str
 9   Образование и ВУЗ                44744 non-null  str
 10  Обновление резюме                44744 non-null  str
 11  Авто                             44744 non-null  str
dtypes: str(12)
memory usage: 437.5 MB

4. Обратите внимание на информацию о числе непустых значений.

In [74]:
df_resume.info()

<class 'pandas.DataFrame'>
RangeIndex: 44744 entries, 0 to 44743
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Пол, возраст                     44744 non-null  str
 1   ЗП                               44744 non-null  str
 2   Ищет работу на должность:        44744 non-null  str
 3   Город, переезд, командировки     44744 non-null  str
 4   Занятость                        44744 non-null  str
 5   График                           44744 non-null  str
 6   Опыт работы                      44576 non-null  str
 7   Последнее/нынешнее место работы  44743 non-null  str
 8   Последняя/нынешняя должность     44742 non-null  str
 9   Образование и ВУЗ                44744 non-null  str
 10  Обновление резюме                44744 non-null  str
 11  Авто                             44744 non-null  str
dtypes: str(12)
memory usage: 437.5 MB

5. Выведите основную статистическую информацию о столбцах.

In [75]:
#ваш код здесь
df_resume.describe()

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
count,44744,44744,44744,44744,44744,44744,44576,44743,44742,44744,44744,44744
unique,16003,690,14929,10063,38,47,44413,30214,16927,40148,18838,2
top,"Мужчина , 32 года , родился 17 сентября 1986",50000 руб.,Системный администратор,"Москва , не готов к переезду , не готов к кома...",полная занятость,полный день,Опыт работы 10 лет 8 месяцев Апрель 2018 — по...,Индивидуальное предпринимательство / частная п...,Системный администратор,Высшее образование 2014 Московский технически...,07.05.2019 09:50,Не указано
freq,18,4064,3099,1261,30026,22727,3,935,2062,4,25,32268

# Преобразование данных

1. Начнем с простого - с признака **"Образование и ВУЗ"**. Его текущий формат это: **<Уровень образования год выпуска ВУЗ специальность...>**. Например:
* Высшее образование 2016 Московский авиационный институт (национальный исследовательский университет)...
* Неоконченное высшее образование 2000  Балтийская государственная академия рыбопромыслового флота…
Нас будет интересовать только уровень образования.

Создайте с помощью функции-преобразования новый признак **"Образование"**, который должен иметь 4 категории: "высшее", "неоконченное высшее", "среднее специальное" и "среднее".

Выполните преобразование, ответьте на контрольные вопросы и удалите признак "Образование и ВУЗ".

Совет: обратите внимание на структуру текста в столбце **"Образование и ВУЗ"**. Гарантируется, что текущий уровень образования соискателя всегда находится в первых 2ух слов и начинается с заглавной буквы. Воспользуйтесь этим.

*Совет: проверяйте полученные категории, например, с помощью метода unique()*

In [76]:
#ваш код здесь
df_resume['Образование'] = df_resume['Образование и ВУЗ'].str.split(' образование ').str[0]
print(df_resume['Образование'].unique())
print(df_resume['Образование'].value_counts())
df_resume.drop('Образование и ВУЗ', axis=1, inplace=True)

['Неоконченное высшее' 'Высшее' 'Среднее специальное' 'Среднее']
Образование
Высшее                 33863
Среднее специальное     5765
Неоконченное высшее     4557
Среднее                  559
Name: count, dtype: int64

2. Теперь нас интересует столбец **"Пол, возраст"**. Сейчас он представлен в формате **<Пол , возраст , дата рождения >**. Например:
* Мужчина , 39 лет , родился 27 ноября 1979 
* Женщина , 21 год , родилась 13 января 2000
Как вы понимаете, нам необходимо выделить каждый параметр в отдельный столбец.

Создайте два новых признака **"Пол"** и **"Возраст"**. При этом важно учесть:
* Признак пола должен иметь 2 уникальных строковых значения: 'М' - мужчина, 'Ж' - женщина. 
* Признак возраста должен быть представлен целыми числами.

Выполните преобразование, ответьте на контрольные вопросы и удалите признак **"Пол, возраст"** из таблицы.

*Совет: обратите внимание на структуру текста в столбце, в части на то, как разделены параметры пола, возраста и даты рождения между собой - символом ' , '. 
Гарантируется, что структура одинакова для всех строк в таблице. Вы можете воспользоваться этим.*

In [77]:
df_resume['Пол'] = df_resume['Пол, возраст'].apply(lambda x: x.split(',')[0][0])
df_resume['Возраст'] = df_resume['Пол, возраст'].apply(lambda x: x.split(',')[1].strip())
df_resume['Возраст'] = df_resume['Возраст'].apply(lambda x: x.split(' ')[0]).astype(int)
print(df_resume['Пол'].value_counts(normalize=True)*100)
print(f"Средний возраст: {df_resume['Возраст'].mean()} лет")
df_resume.drop('Пол, возраст', axis=1, inplace=True)

Пол
М    80.929287
Ж    19.070713
Name: proportion, dtype: float64
Средний возраст: 32.19674146254246 лет

3. Следующим этапом преобразуем признак **"Опыт работы"**. Его текущий формат - это: **<Опыт работы: n лет m месяцев, периоды работы в различных компаниях…>**. 

Из столбца нам необходимо выделить общий опыт работы соискателя в месяцах, новый признак назовем "Опыт работы (месяц)"

Для начала обсудим условия решения задачи:
* Во-первых, в данном признаке есть пропуски. Условимся, что если мы встречаем пропуск, оставляем его как есть (функция-преобразование возвращает NaN)
* Во-вторых, в данном признаке есть скрытые пропуски. Для некоторых соискателей в столбце стоит значения "Не указано". Их тоже обозначим как NaN (функция-преобразование возвращает NaN)
* В-третьих, нас не интересует информация, которая описывается после указания опыта работы (периоды работы в различных компаниях)
* В-четвертых, у нас есть проблема: опыт работы может быть представлен только в годах или только месяцах. Например, можно встретить следующие варианты:
    * Опыт работы 3 года 2 месяца…
    * Опыт работы 4 года…
    * Опыт работы 11 месяцев…
    * Учитывайте эту особенность в вашем коде

Учитывайте эту особенность в вашем коде

В результате преобразования у вас должен получиться столбец, содержащий информацию о том, сколько месяцев проработал соискатель.
Выполните преобразование, ответьте на контрольные вопросы и удалите столбец **"Опыт работы"** из таблицы.

In [78]:
def work_months(in_str):
    if in_str == 'Не указано' or pd.isna(in_str):
        return np.nan
    str_splt = in_str.split(' ')
    if 'месяц' in str_splt[3]:
        return int(str_splt[2])
    if len(str_splt) >=5 and 'месяц' in str_splt[5]:
        return int(str_splt[2]) * 12 + int(str_splt[4])
    if 'год' in str_splt[3] or 'лет' in str_splt[3]:
        return int(str_splt[2]) * 12
    return -1 # ошибки парсинга
df_resume['Опыт работы (месяц)'] = df_resume['Опыт работы'].apply(work_months)
print(df_resume[df_resume['Опыт работы (месяц)']==-1].shape[0])
print(df_resume['Опыт работы (месяц)'].median())
df_resume.drop('Опыт работы', axis=1, inplace=True)

0
100.0

4. Хорошо идем! Следующий на очереди признак "Город, переезд, командировки". Информация в нем представлена в следующем виде: **<Город , (метро) , готовность к переезду (города для переезда) , готовность к командировкам>**. В скобках указаны необязательные параметры строки. Например, можно встретить следующие варианты:

* Москва , не готов к переезду , готов к командировкам
* Москва , м. Беломорская , не готов к переезду, не готов к командировкам
* Воронеж , готов к переезду (Сочи, Москва, Санкт-Петербург) , готов к командировкам

Создадим отдельные признаки **"Город"**, **"Готовность к переезду"**, **"Готовность к командировкам"**. При этом важно учесть:

* Признак **"Город"** должен содержать только 4 категории: "Москва", "Санкт-Петербург" и "город-миллионник" (их список ниже), остальные обозначьте как "другие".

    Список городов-миллионников:
    
   <code>million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань', 'Челябинск','Омск', 'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж','Волгоград']
    </code>
    Инфорация о метро, рядом с которым проживает соискатель нас не интересует.
* Признак **"Готовность к переезду"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к переезду в признаке "Город, переезд, командировки". Например:
    * … , готов к переезду , …
    * … , не готова к переезду , …
    * … , готова к переезду (Москва, Санкт-Петербург, Ростов-на-Дону)
    * … , хочу переехать (США) , …
    
    Нас интересует только сам факт возможности или желания переезда.
* Признак **"Готовность к командировкам"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к командировкам в признаке "Город, переезд, командировки". Например:
    * … , готов к командировкам , … 
    * … , готова к редким командировкам , …
    * … , не готов к командировкам , …
    
    Нас интересует только сам факт готовности к командировке.
    
    Еще один важный факт: при выгрузки данных у некоторых соискателей "потерялась" информация о готовности к командировкам. Давайте по умолчанию будем считать, что такие соискатели не готовы к командировкам.
    
Выполните преобразования и удалите столбец **"Город, переезд, командировки"** из таблицы.

*Совет: обратите внимание на то, что структура текста может меняться в зависимости от указания ближайшего метро. Учите это, если будете использовать порядок слов в своей программе.*

In [79]:
def cell_parsing(in_str):

    cap_cities = ['Москва','Санкт-Петербург']
    million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань',
        'Челябинск','Омск', 'Самара', 'Ростов-на-Дону', 'Уфа',
        'Красноярск', 'Пермь', 'Воронеж','Волгоград']

    spl_str = in_str.split(',')
    citi = spl_str[0].strip()
    if citi in million_cities:
        citi = 'город-миллионник'
    elif not citi in cap_cities:
        citi = 'другие'

    find_first = lambda spl_str, list: next((' '+s for s in spl_str for l in list if l in s), ' не ')

    pereezd = not ' не ' in find_first(spl_str, ["переезду","переехать"])
    komand  = not ' не ' in find_first(spl_str, ["командиров"])
    return pd.Series([citi, pereezd, komand])

df_resume[["Город",
    "Готовность к переезду",
    "Готовность к командировкам"]] = df_resume["Город, переезд, командировки"].apply(cell_parsing)
print(df_resume["Город"].value_counts(normalize=True)*100)
print((df_resume["Готовность к переезду"]&df_resume["Готовность к командировкам"]).mean()*100)
df_resume.drop("Город, переезд, командировки", axis=1, inplace=True)

Город
Москва              37.146880
другие              35.432684
город-миллионник    16.386555
Санкт-Петербург     11.033882
Name: proportion, dtype: float64
31.86572501340962

5. Рассмотрим поближе признаки **"Занятость"** и **"График"**. Сейчас признаки представляют собой набор категорий желаемой занятости (полная занятость, частичная занятость, проектная работа, волонтерство, стажировка) и желаемого графика работы (полный день, сменный график, гибкий график, удаленная работа, вахтовый метод).
На сайте hh.ru соискатель может указывать различные комбинации данных категорий, например:
* полная занятость, частичная занятость
* частичная занятость, проектная работа, волонтерство
* полный день, удаленная работа
* вахтовый метод, гибкий график, удаленная работа, полная занятость

Такой вариант признаков имеет множество различных комбинаций, а значит множество уникальных значений, что мешает анализу. Нужно это исправить!

Давайте создадим признаки-мигалки для каждой категории: если категория присутствует в списке желаемых соискателем, то в столбце на месте строки рассматриваемого соискателя ставится True, иначе - False.

Такой метод преобразования категориальных признаков называется One Hot Encoding и его схема представлена на рисунке ниже:
<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/ohe.jpg>
Выполните данное преобразование для признаков "Занятость" и "График", ответьте на контрольные вопросы, после чего удалите их из таблицы

In [80]:
df_resume[['полный день',
    'сменный график'
    , 'гибкий график'
    , 'удаленная работа'
    , 'вахтовый метод']]  \
    = df_resume['График'].apply(lambda x: pd.Series([
        'полный день' in x
        , 'сменный график' in x
        , 'гибкий график' in x
        , 'удаленная работа' in x
        , 'вахтовый метод' in x]
        ))
df_resume[['полная занятость'
    , 'частичная занятость'
    , 'проектная работа'
    , 'волонтерство'
    , 'стажировка'
    ]]  \
    = df_resume['Занятость'].apply(lambda x: pd.Series([
        'полная занятость' in x
        , 'частичная занятость' in x
        , 'проектная работа' in x
        , 'волонтерство' in x
        , 'стажировка' in x]
        ))
# 'гибкий график, полный день, сменный график, вахтовый метод, удаленная работа',
print((df_resume['проектная работа']&df_resume['волонтерство']).sum())
print((df_resume['вахтовый метод']&df_resume['гибкий график']).sum())
df_resume.drop(['Занятость','График'], axis=1, inplace=True)

436
2311

6. (2 балла) Наконец, мы добрались до самого главного и самого важного - признака заработной платы **"ЗП"**. 
В чем наша беда? В том, что помимо желаемой заработной платы соискатель указывает валюту, в которой он бы хотел ее получать, например:
* 30000 руб.
* 50000 грн.
* 550 USD

Нам бы хотелось видеть заработную плату в единой валюте, например, в рублях. Возникает вопрос, а где взять курс валют по отношению к рублю?

На самом деле язык Python имеет в арсенале огромное количество возможностей получения данной информации, от обращения к API Центробанка, до использования специальных библиотек, например pycbrf. Однако, это не тема нашего проекта.

Поэтому мы пойдем в лоб: обратимся к специальным интернет-ресурсам для получения данных о курсе в виде текстовых файлов. Например, MDF.RU, данный ресурс позволяет удобно экспортировать данные о курсах различных валют и акций за указанные периоды в виде csv файлов. Мы уже сделали выгрузку курсов валют, которые встречаются в наших данных за период с 29.12.2017 по 05.12.2019. Скачать ее вы можете **на платформе**

Создайте новый DataFrame из полученного файла. В полученной таблице нас будут интересовать столбцы:
* "currency" - наименование валюты в ISO кодировке,
* "date" - дата, 
* "proportion" - пропорция, 
* "close" - цена закрытия (последний зафиксированный курс валюты на указанный день).


Перед вами таблица соответствия наименований иностранных валют в наших данных и их общепринятых сокращений, которые представлены в нашем файле с курсами валют. Пропорция - это число, за сколько единиц валюты указан курс в таблице с курсами. Например, для казахстанского тенге курс на 20.08.2019 составляет 17.197 руб. за 100 тенге, тогда итоговый курс равен - 17.197 / 100 = 0.17197 руб за 1 тенге.
Воспользуйтесь этой информацией в ваших преобразованиях.

<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/table.jpg>


Осталось только понять, откуда брать дату, по которой определяется курс? А вот же она - в признаке **"Обновление резюме"**, в нем содержится дата и время, когда соискатель выложил текущий вариант своего резюме. Нас интересует только дата, по ней бы и будем сопоставлять курсы валют.

Теперь у нас есть вся необходимая информация для того, чтобы создать признак "ЗП (руб)" - заработная плата в рублях.

После ответа на контрольные вопросы удалите исходный столбец заработной платы "ЗП" и все промежуточные столбцы, если вы их создавали.

Итак, давайте обсудим возможный алгоритм преобразования: 
1. Перевести признак "Обновление резюме" из таблицы с резюме в формат datetime и достать из него дату. В тот же формат привести признак "date" из таблицы с валютами.
2. Выделить из столбца "ЗП" сумму желаемой заработной платы и наименование валюты, в которой она исчисляется. Наименование валюты перевести в стандарт ISO согласно с таблицей выше.
3. Присоединить к таблице с резюме таблицу с курсами по столбцам с датой и названием валюты (подумайте, какой тип объединения надо выбрать, чтобы в таблице с резюме сохранились данные о заработной плате, изначально представленной в рублях). Значение close для рубля заполнить единицей 1 (курс рубля самого к себе)
4. Умножить сумму желаемой заработной платы на присоединенный курс валюты (close) и разделить на пропорцию (обратите внимание на пропуски после объединения в этих столбцах), результат занести в новый столбец "ЗП (руб)".

In [88]:
# df_resume['ЗП'].str.split(' ').str[1].unique()
dict_curr=dict(zip(['руб.', 'бел.руб.', 'KZT', 'EUR', 'USD', 'грн.', 'сум', 'KGS',
       'AZN'],['RUR','BYN','KZT','EUR','USD','UAH','UZS','KGS',
       'AZN']))

df_curr = pd.read_csv('exchangerates.csv')

df_curr['date'] = pd.to_datetime(df_curr['date'],format='%d/%m/%y').dt.date

df_calc = pd.concat(
    [pd.to_datetime(df_resume['Обновление резюме'],format='%d.%m.%Y %H:%M').dt.date
        , df_resume['ЗП'].str.split(' ').apply(lambda x: pd.Series([float(x[0]),dict_curr[x[1]]]))
        ]
    , axis=1
    )

df_calc.columns=['date','sum','currency']
df_calc = df_calc.merge(df_curr, on=['date','currency'], how='left')

df_calc.loc[df_calc['currency']=='RUR',['close','proportion']]=1
df_resume['ЗП (руб)'] = df_calc['close'] * df_calc['sum'] / df_calc['proportion']
df_resume['ЗП (руб)'] = df_resume['ЗП (руб)']

print(df_resume['ЗП (руб)'].median())
df_resume.drop('ЗП', axis=1, inplace=True)
# del df_calc

59019.0

In [89]:
df_resume.info()

<class 'pandas.DataFrame'>
RangeIndex: 44744 entries, 0 to 44743
Data columns (total 23 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Ищет работу на должность:        44744 non-null  str
 1   Последнее/нынешнее место работы  44743 non-null  str
 2   Последняя/нынешняя должность     44742 non-null  str
 3   Обновление резюме                44744 non-null  str
 4   Авто                             44744 non-null  str
 5   Образование                      44744 non-null  object
 6   Пол                              44744 non-null  str
 7   Возраст                          44744 non-null  int64
 8   Опыт работы (месяц)              44574 non-null  float64
 9   Город                            44744 non-null  str
 10  Готовность к переезду            44744 non-null  bool
 11  Готовность к командировкам       44744 non-null  bool
 12  полный день                      44744 non-null  bool
 13  сменный график                   44744 non-null  bool
 14  гибкий график                    44744 non-null  bool
 15  удаленная работа                 44744 non-null  bool
 16  вахтовый метод                   44744 non-null  bool
 17  полная занятость                 44744 non-null  bool
 18  частичная занятость              44744 non-null  bool
 19  проектная работа                 44744 non-null  bool
 20  волонтерство                     44744 non-null  bool
 21  стажировка                       44744 non-null  bool
 22  ЗП (руб)                         44744 non-null  float64
dtypes: bool(12), float64(2), int64(1), object(1), str(7)
memory usage: 13.1+ MB

# Исследование зависимостей в данных

1. Постройте распределение признака **"Возраст"**. Опишите распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится возраст большинства соискателей? Есть ли аномалии для признака возраста, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [97]:
df_graf = df_resume['Возраст']

fig = make_subplots(
    rows=2,
    cols=1,
    vertical_spacing=0
    , shared_xaxes=True
)

fig.add_trace(go.Histogram(
        x=df_graf,
        nbinsx=100
        ),
    row=1,
    col=1
)

fig.add_trace(go.Box(
        x=df_graf,
        name=''),
    row=2,
    col=1
)
#
fig.update_layout(
    title='Распределение признака "Возраст"',
    bargap=0.05,
    height=700,
    showlegend=False
    )
#
fig.update_xaxes(
    title_text='Возраст',
    row=2,
    col=1
    )
fig.update_yaxes(
    title_text='Количество соискателей',
    row=1,
    col=1
    )
fig.show()
fig.write_html("1.html", include_plotlyjs="cdn", full_html=False)

Модальное значение возраста соискателей равно 30, предельные значения признака равны 14 и 49, возраст большинства соискателей (50%) в интервале от 27 до 36 лет, к аномалиям признака можно отнести значение равное 100.

2. Постройте распределение признака **"Опыт работы (месяц)"**. Опишите данное распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится опыт работы большинства соискателей? Есть ли аномалии для признака опыта работы, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [96]:
df_graf = df_resume['Опыт работы (месяц)']

fig = make_subplots(
    rows=2,
    cols=1,
    vertical_spacing=0
    , shared_xaxes=True
)

fig.add_trace(go.Histogram(
    x=df_graf,
    nbinsx=100
),
    row=1,
    col=1
)

fig.add_trace(go.Box(
    x=df_graf,
    name=''),
    row=2,
    col=1
)
#
fig.update_layout(
    title='Распределение признака "Опыт работы (месяц)"',
    bargap=0.05,
    height=700,
    showlegend=False
)
#
fig.update_xaxes(
    title_text='Количество месяцев',
    row=2,
    col=1
)
fig.update_yaxes(
    title_text='Количество соискателей',
    row=1,
    col=1
)
fig.show()
fig.write_html("2.html", include_plotlyjs="cdn", full_html=False)

Мода распределения (согласно графика) находится в интервале 80-99, предельные значения признака равны 1 и 299, опыт работы большинства соискателей находится в интервале 57-154. К аномалии признака можно отнести опыт работы равный 1188 месяцам

3. Постройте распределение признака **"ЗП (руб)"**. Опишите данное распределение, отвечая на следующие вопросы: каковы предельные значения признака, в каком примерном интервале находится заработная плата большинства соискателей? Есть ли аномалии для признака возраста? Обратите внимание на гигантские размеры желаемой заработной платы.
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [95]:
df_graf = df_resume[df_resume['ЗП (руб)']<=1000000]['ЗП (руб)']
# df_graf = df_resume['ЗП (руб)']
fig = make_subplots(
    rows=2,
    cols=1
    , vertical_spacing=0
    , shared_xaxes=True
)

fig.add_trace(
    go.Histogram(
        x=df_graf
        , nbinsx=100
        ),
    row=1,
    col=1
)

fig.add_trace(
    go.Box(
        x=df_graf,
        name=''
        ),
    row=2,
    col=1
)

fig.update_layout(
    title='Распределение признака "ЗП (руб)"',
    bargap=0.05,
    height=700,
    showlegend=False
    )

fig.update_xaxes(
    title_text='Зарплата'
    , row=1
    , col=1
    )

fig.update_yaxes(
    title_text='Количество соискателей'
    , row=1
    , col=1
    # , type='log'
    )

fig.show()
fig.write_html("3.html", include_plotlyjs="cdn", full_html=False)

Предельные значения признака равны от 1 руб. до 181 тыс.руб. , заработная плата большинства соискателей находится в интервале от 37 тыс.руб. до 95 тыс.руб.  В качестве аномалий можно принять единичные выбросы с уровнем зарплаты более 1 млн.руб. (учитывая основной массив запросов)

4. Постройте диаграмму, которая показывает зависимость **медианной** желаемой заработной платы (**"ЗП (руб)"**) от уровня образования (**"Образование"**). Используйте для диаграммы данные о резюме, где желаемая заработная плата меньше 1 млн рублей.
*Сделайте выводы по представленной диаграмме: для каких уровней образования наблюдаются наибольшие и наименьшие уровни желаемой заработной платы? Как вы считаете, важен ли признак уровня образования при прогнозировании заработной платы?*

In [99]:
df_graf = df_resume[df_resume['ЗП (руб)']<=1000000].groupby(['Образование']).agg({'ЗП (руб)':'median'}).reset_index()
fig = px.bar(
    data_frame=df_graf,
    x='Образование',
    y='ЗП (руб)',
    color='Образование',
    text = 'ЗП (руб)',
    orientation='v',
    height=500,
    title='Зависимость медианной желаемой заработной платы от образования'
)

fig.update_traces(showlegend=False)
fig.show()
fig.write_html("4.html", include_plotlyjs="cdn", full_html=False)

Наибольший уровень желаемой зарплаты наблюдаются для соискателей с высшим образованием и наименьший уровень для соискателей со средним и средним-специальным образованием. Признак уровня образования важен для прогнозирования желаемой зарплаты, т.к. люди с высшим образованием имеют более высокую квалификацию.

5. Постройте диаграмму, которая показывает распределение желаемой заработной платы (**"ЗП (руб)"**) в зависимости от города (**"Город"**). Используйте для диаграммы данные о резюме, где желая заработная плата меньше 1 млн рублей.
*Сделайте выводы по полученной диаграмме: как соотносятся медианные уровни желаемой заработной платы и их размах в городах? Как вы считаете, важен ли признак города при прогнозировании заработной платы?*

In [100]:
df_graf = df_resume[df_resume['ЗП (руб)']<=1000000]

fig = px.box(df_graf
    , y='Город'
    , x='ЗП (руб)'
    , color='Город'
    , title='Распределение желаемой заработной платы в зависимости от города'
    )
fig.update_layout(
    showlegend=False
    )
fig.update_yaxes(
    title_text=''
    )
fig.show()
fig.write_html("5.html", include_plotlyjs="cdn", full_html=False)

На графиках наблюдается следующая зависимость: чем выше уровень медианной желаемой зарплаты, тем больше ее размах. Признак "Город" важен в части выделения соискателей из Москвы и Санкт-Петербурга, так как их ожидания в целом явно выше по отношению с остальными городами

6. Постройте **многоуровневую столбчатую диаграмму**, которая показывает зависимость медианной заработной платы (**"ЗП (руб)"**) от признаков **"Готовность к переезду"** и **"Готовность к командировкам"**. Проанализируйте график, сравнив уровень заработной платы в категориях.

In [101]:
# df_graf = df_resume[df_resume['ЗП (руб)']<=1000000].groupby(['Готовность к переезду'
#         ,'Готовность к командировкам']).agg({'ЗП (руб)':'median'}).reset_index()
df_graf = df_resume.groupby(['Готовность к переезду'
        ,'Готовность к командировкам'],as_index=False).agg({'ЗП (руб)':'median'}).reset_index()

repl_dict = {True:'Готов', False:'Не готов'}
df_graf = df_graf.replace({
    'Готовность к переезду': repl_dict,
    'Готовность к командировкам': repl_dict
    })
fig = px.bar(
    data_frame=df_graf,
    color='Готовность к командировкам',
    y='ЗП (руб)',
    x='Готовность к переезду',
    text = 'ЗП (руб)',
    barmode='group',
    height=500,
    title='Зависимость медианной заработной платы <br>от признаков "Готовность к переезду" и "Готовность к командировкам"',
    labels={
        'False': 'не готов',
        'True': 'готов'
        }
)

fig.show()
fig.write_html("6.html", include_plotlyjs="cdn", full_html=False)

Согласие на командировки значительно сильнее влияет на уровень ожидаемой заработной платы, нежели готовность к переезду. Возможно потому, что готовность к переезду может быть обусловлена желанием сменить место жительства, а частые командировки рассматриваются как некомфортные условия работы.

7. Постройте сводную таблицу, иллюстрирующую зависимость **медианной** желаемой заработной платы от возраста (**"Возраст"**) и образования (**"Образование"**). На полученной сводной таблице постройте **тепловую карту**. Проанализируйте тепловую карту, сравнив показатели внутри групп.

In [102]:
pvt_table = pd.pivot_table(
    df_resume,
    values='ЗП (руб)',
    index='Образование',
    columns='Возраст',
    aggfunc='median',
    fill_value=0     # заполняем пропуски нулями
)

fig = go.Figure(data = go.Heatmap(
    z=pvt_table.values,
    x=pvt_table.columns,
    y=pvt_table.index,
    text=pvt_table.values,
    colorbar={'title':'ЗП (руб)'}
    ))

fig.update_layout(
    title='Зависимость медианной желаемой заработной платы от возраста и образования',
    xaxis_title='Возраст',
    yaxis_title='Образование'
    )
fig.show()
fig.write_html("7.html", include_plotlyjs="cdn", full_html=False)

Наиболее высокие зарплатные ожидания наблюдаются в группе от 30 до 55 лет с пиком в районе 40 лет соискателей с высшим образованием, они ранее выходят на более высокие чем другие группы уровни зарплат и дольше их сохраняют. Ярко выражена более высокая чем у других групп продолжительность активности соискателей с высшим образованием. В целом можно сделать вывод: чем выше образование, тем более длительная карьера и выше уровень зарплат.

8. Постройте **диаграмму рассеяния**, показывающую зависимость опыта работы (**"Опыт работы (месяц)"**) от возраста (**"Возраст"**). Опыт работы переведите из месяцев в года, чтобы признаки были в едином масштабе. Постройте на графике дополнительно прямую, проходящую через точки (0, 0) и (100, 100). Данная прямая соответствует значениям, когда опыт работы равен возрасту человека. Точки, лежащие на этой прямой и выше нее - аномалии в наших данных (опыт работы больше либо равен возрасту соискателя)

In [103]:
df_graf = df_resume[['Опыт работы (месяц)','Возраст']].reset_index()
df_graf['Опыт работы (месяц)'] = df_graf['Опыт работы (месяц)'].fillna(0)
df_graf['Опыт работы (год)'] = (df_graf['Опыт работы (месяц)'] / 12)

fig = px.scatter(
    df_graf,
    x='Возраст',
    y='Опыт работы (год)',
    title='Зависимость опыта работы от возраста.',
    )
fig.add_scatter(x=[0, 100], y=[0, 100],
                mode='lines', name='возраст=опыту',
                line=dict(color='blue', width=3, dash='dash'))
fig.show()

df_graf[df_graf['Опыт работы (год)']>df_graf['Возраст']].shape[0]

fig.write_html("8.html", include_plotlyjs="cdn", full_html=False)

Кроме выбросов выше линии "возраст=опыт", к анамалиям можно отнести точки близкие к линии снизу, предполагающие опыт работы с возраста менее 10 лет. Примерно с 50-55 лет наблюдается тенденция снижение соискателей с минимальным опытом роботы, что может говорить о не желании менять направление деятельности соискателей старшего возраста.

**Дополнительные баллы**

Для получения 2 дополнительных баллов по разведывательному анализу постройте еще два любых содержательных графика или диаграммы, которые помогут проиллюстрировать влияние признаков/взаимосвязь между признаками/распределения признаков. Приведите выводы по ним. Желательно, чтобы в анализе участвовали признаки, которые мы создавали ранее в разделе "Преобразование данных".

In [104]:
df_graf = df_resume.groupby(['Образование'
        ,'Авто'],as_index=False).agg({'ЗП (руб)':'median'}).reset_index()

fig = px.bar(
    data_frame=df_graf,
    color='Авто',
    y='ЗП (руб)',
    x='Образование',
    text = 'ЗП (руб)',
    barmode='group',
    height=500,
    title='Зависимость медианной заработной платы <br>от признака наличия автомобиля по группам образования',
)

fig.show()
fig.write_html("9_1.html", include_plotlyjs="cdn", full_html=False)

Наличие автомобиля может являться маркером более высоких зарплатных ожиданий

In [105]:
df_graf = df_resume.groupby(['Образование']).agg({'Опыт работы (месяц)':'median'}).reset_index()
fig = px.bar(
    data_frame=df_graf,
    x='Образование',
    y='Опыт работы (месяц)',
    color='Образование',
    text = 'Опыт работы (месяц)',
    orientation='v',
    height=500,
    title='Зависимость медианного опыта работы от уровня образования'
)

fig.update_traces(showlegend=False)
fig.show()
fig.write_html("9_2.html", include_plotlyjs="cdn", full_html=False)

Люди с высшим образованием менее склонны к смене направления деятельности

# Очистка данных

1. Начнем с дубликатов в наших данных. Найдите **полные дубликаты** в таблице с резюме и удалите их.

In [106]:
print(df_resume[df_resume.duplicated(subset=df_resume.columns)].shape[0])
df_resume = df_resume.drop_duplicates()

158

2. Займемся пропусками. Выведите информацию **о числе пропусков** в столбцах.

In [107]:
df=df_resume.shape[0]-df_resume.count()
df[df>0]

Последнее/нынешнее место работы      1
Последняя/нынешняя должность         2
Опыт работы (месяц)                168
dtype: int64

3. Итак, у нас есть пропуски в 3ех столбцах: **"Опыт работы (месяц)"**, **"Последнее/нынешнее место работы"**, **"Последняя/нынешняя должность"**. Поступим следующим образом: удалите строки, где есть пропуск в столбцах с местом работы и должностью. Пропуски в столбце с опытом работы заполните **медианным** значением.

In [108]:
df_resume = df_resume.dropna(subset=['Последнее/нынешнее место работы', 'Последняя/нынешняя должность'])
median = df_resume['Опыт работы (месяц)'].median()
df_resume['Опыт работы (месяц)'] = df_resume['Опыт работы (месяц)'].fillna(median)
df_resume['Опыт работы (месяц)'].mean()

np.float64(114.35831239906693)

4. Мы добрались до ликвидации выбросов. Сначала очистим данные вручную. Удалите резюме, в которых указана заработная плата либо выше 1 млн. рублей, либо ниже 1 тыс. рублей.

In [109]:
zp_filter = (df_resume['ЗП (руб)']>1000000)|(df_resume['ЗП (руб)']<1000)
print(zp_filter.sum())
df_resume = df_resume[~zp_filter]

89

5. В процессе разведывательного анализа мы обнаружили резюме, в которых **опыт работы в годах превышал возраст соискателя**. Найдите такие резюме и удалите их из данных

In [110]:
df_filter = (df_resume['Опыт работы (месяц)']/12>df_resume['Возраст'])
print(df_filter.sum())
df_resume.drop(df_filter[df_filter].index, inplace=True)

7

6. В результате анализа мы обнаружили потенциальные выбросы в признаке **"Возраст"**. Это оказались резюме людей чересчур преклонного возраста для поиска работы. Попробуйте построить распределение признака в **логарифмическом масштабе**. Добавьте к графику линии, отображающие **среднее и границы интервала метода трех сигм**. Напомним, сделать это можно с помощью метода axvline. Например, для построение линии среднего будет иметь вид:

`histplot.axvline(log_age.mean(), color='k', lw=2)`

В какую сторону асимметрично логарифмическое распределение? Напишите об этом в комментарии к графику.
Найдите выбросы с помощью метода z-отклонения и удалите их из данных, используйте логарифмический масштаб. Давайте сделаем послабление на **1 сигму** (возьмите 4 сигмы) в **правую сторону**.

Выведите таблицу с полученными выбросами и оцените, с каким возрастом соискатели попадают под категорию выбросов?

In [112]:
log_df = np.log(df_resume['Возраст'] + 1)

mu = log_df.mean()
sigma = log_df.std()
lower_bound = mu - 3 * sigma
upper_bound = mu + 3 * sigma

fig = px.histogram(
    log_df,
    title='Распределение признака "Возраст" ( log )',
    nbins=80,
    log_y=True
    )

fig.add_vline(mu , line_color="red")
fig.add_vline(lower_bound, line_color="red", line_dash="dash")
fig.add_vline(upper_bound, line_color="red", line_dash="dash")

fig.update_layout(
    showlegend=False,
    xaxis_title='Возраст',
    yaxis_title='Количество соискателей'
    )
fig.show()
fig.write_html("clear_1.html", include_plotlyjs="cdn", full_html=False)
print('правостороннее' if log_df.skew()>0 else 'левостороннее')

upper_bound_h = mu + 4 * sigma
out_fltr = (log_df < lower_bound) | (log_df > upper_bound_h)
print(out_fltr.sum())
display(df_resume[out_fltr])
df_resume=df_resume[~out_fltr]

правостороннее
3

,Ищет работу на должность:,Последнее/нынешнее место работы,Последняя/нынешняя должность,Обновление резюме,Авто,Образование,Пол,Возраст,Опыт работы (месяц),Город,...,сменный график,гибкий график,удаленная работа,вахтовый метод,полная занятость,частичная занятость,проектная работа,волонтерство,стажировка,ЗП (руб)
31137,Менеджер по работе с клиентами,"ООО ""ФёрстКэшКомпани""",Менеджер по работе с клиентами,06.04.2019 09:13,Не указано,Среднее,М,15,2.0,Санкт-Петербург,...,True,True,True,False,False,True,False,False,False,10000.0
32950,Тестировщик игр,OOO ЖМЫХ,Тестировщик ПО,09.04.2019 16:02,Не указано,Среднее специальное,М,15,3.0,другие,...,False,False,False,False,True,False,False,False,False,2000.0
33654,Frontend-разработчик,Freelance,Frontend-разработчик,19.04.2019 23:27,Не указано,Среднее специальное,М,100,30.0,Санкт-Петербург,...,False,True,True,False,True,True,True,False,True,60000.0

Распределение асимметрично в правую сторону. Под категорию выбросов попали соискатели с возрастом 15 и 100 лет.